version: '3.1'
services:
  postgres:
    image: postgres:10
    container_name: backend_postgres
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres